export enum EReduxTypes {
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  UPDATE_LOADING_COMPONENT = 'UPDATE_LOADING_COMPONENT',
  FIND_POKEMONS = 'FIND_POKEMONS',
  GET_POKEMON = 'GET_POKEMON',
}
