export const HEADER_HEIGHT = 55;
export const MAIN_CONTAINER_SIDES_PADDING = 60;
export const MAIN_CONTAINER_SIDES_PADDING_MOBILE = 30;
export const MAIN_CONTAINER_MAX_WIDTH = 1600;

export enum COLORS {
  WHITE = '#FFF',
  BLACK = '#000',
  L_BLUE_A = '#3d79e0',
  L_GREEN ='#DFF9F2',
  L_YELLOW = '#DFE7F9',
  L_PURPLE = '#F9DFF7',
  L_RED = '#F9DFE9',
  L_BLUE = '#F9EBDF',
  L_ORANGE = '#F2F9DF',
};
